print("========= DAILY WORKOUT PLAN =========")
print("Day       Workout Type     Duration")
print("Monday    Chest + Triceps     45 min")
print("Tuesday   Back + Biceps       50 min")
print("Wednesday Legs + Core         60 min")
print("Thursday  Shoulders + Cardio  40 min")
print("Friday    Full Body HIIT      45 min")
print("Saturday  Yoga & Stretching   30 min")
print("Sunday    Rest Day ")
print("======================================")
