print("   ____        _   _                 ")
print("  |  _ \ _   _| |_| |__   ___  _ __  ")
print("  | |_) | | | | __| '_ \ / _ \| '_ \ ")
print("  |  __/| |_| | |_| | | | (_) | | | |")
print("  |_|    \__, |\__|_| |_|\___/|_| |_|")
print("         |___/                      ")
print("      Welcome to the Python World!")
