print("========= RESULT CARD =========")
print("Name       : Yash Tayade")
print("Class      : Second Year IT")
print("Subject           Marks")
print("Maths              92")
print("DSA                88")
print("Python             95")
print("OS                 89")
print("------------------------------")
print("Total:             364 / 400")
print("Percentage:        91.0%")
print("Grade:             A+")
print("================================")
